version: '3.7'
services:
  ollama:
    image: ollama/ollama  
    container_name: ollama
    runtime: nvidia  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      #- ollamavolume:/root/.ollama
       - /home/alok/workdir/ollamamodels:/root/.ollama
    ports:
      - "11434:11434"
volumes:
  ollamavolume:
